name: 🐞 Bug Report - Tale of Biomes
description: Report a bug or issue with the Tale of Biomes modification.
labels: Bug
title: "[Bug]: "
body:
  - type: textarea
    attributes:
      label: Issue information
      description: Provide us with information about the bug/issue
      placeholder: |
        - How does the bug/issue behave?
        - What feature is the bug related to?
        - When does the issue happen?
        - What was the last thing you did before it happened?
        - Is this a visual bug/issue or is it a physical one (provide a video URL or screenshot if needed)?
        - Does the game crash (provide a crash report if so)?
        - Provide any additional context that may help with figuring out the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide us with a list of steps on how to reproduce the issue
      placeholder: |
        1. Place your mod's grass block.
        2. Break the block in survival.
        3. The block will not drop dirt but rather grass still.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Build information
      description: List the API and modification build information
      placeholder: |
        Tale Of Biomes: r0.1.0-indev
        Forge: 1.20.1
    validations:
      required: true
