
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.nwtg.taleofbiomes.init;

import net.nwtg.taleofbiomes.block.YellowPiruffBedTopBlock;
import net.nwtg.taleofbiomes.block.YellowPiruffBedBlock;
import net.nwtg.taleofbiomes.block.WindowBlueprintBlock;
import net.nwtg.taleofbiomes.block.WildIndigoFlowerPotBlock;
import net.nwtg.taleofbiomes.block.WildIndigoBlock;
import net.nwtg.taleofbiomes.block.WallBlueprintBlock;
import net.nwtg.taleofbiomes.block.ToolHandleBlockBlock;
import net.nwtg.taleofbiomes.block.TilledSoilW4S4Block;
import net.nwtg.taleofbiomes.block.TilledSoilW4S3Block;
import net.nwtg.taleofbiomes.block.TilledSoilW4S2Block;
import net.nwtg.taleofbiomes.block.TilledSoilW4S1Block;
import net.nwtg.taleofbiomes.block.TilledSoilW4S0Block;
import net.nwtg.taleofbiomes.block.TilledSoilW3S4Block;
import net.nwtg.taleofbiomes.block.TilledSoilW3S3Block;
import net.nwtg.taleofbiomes.block.TilledSoilW3S2Block;
import net.nwtg.taleofbiomes.block.TilledSoilW3S1Block;
import net.nwtg.taleofbiomes.block.TilledSoilW3S0Block;
import net.nwtg.taleofbiomes.block.TilledSoilW2S4Block;
import net.nwtg.taleofbiomes.block.TilledSoilW2S3Block;
import net.nwtg.taleofbiomes.block.TilledSoilW2S2Block;
import net.nwtg.taleofbiomes.block.TilledSoilW2S1Block;
import net.nwtg.taleofbiomes.block.TilledSoilW2S0Block;
import net.nwtg.taleofbiomes.block.TilledSoilW1S4Block;
import net.nwtg.taleofbiomes.block.TilledSoilW1S3Block;
import net.nwtg.taleofbiomes.block.TilledSoilW1S2Block;
import net.nwtg.taleofbiomes.block.TilledSoilW1S1Block;
import net.nwtg.taleofbiomes.block.TilledSoilW1S0Block;
import net.nwtg.taleofbiomes.block.TilledSoilW0S4Block;
import net.nwtg.taleofbiomes.block.TilledSoilW0S3Block;
import net.nwtg.taleofbiomes.block.TilledSoilW0S2Block;
import net.nwtg.taleofbiomes.block.TilledSoilW0S1Block;
import net.nwtg.taleofbiomes.block.TilledSoilBlock;
import net.nwtg.taleofbiomes.block.ThatchStairsBlock;
import net.nwtg.taleofbiomes.block.ThatchSlabBlock;
import net.nwtg.taleofbiomes.block.ThatchBlockBlock;
import net.nwtg.taleofbiomes.block.TallGrass2Block;
import net.nwtg.taleofbiomes.block.TallGrass1Block;
import net.nwtg.taleofbiomes.block.TallGrass0Block;
import net.nwtg.taleofbiomes.block.StrippedPiruffWoodBlock;
import net.nwtg.taleofbiomes.block.StrippedPiruffLogBlock;
import net.nwtg.taleofbiomes.block.StoneBlock;
import net.nwtg.taleofbiomes.block.SandBlock;
import net.nwtg.taleofbiomes.block.RoseShrubBlock;
import net.nwtg.taleofbiomes.block.RiceCrop7Block;
import net.nwtg.taleofbiomes.block.RiceCrop6Block;
import net.nwtg.taleofbiomes.block.RiceCrop5Block;
import net.nwtg.taleofbiomes.block.RiceCrop4Block;
import net.nwtg.taleofbiomes.block.RiceCrop3Block;
import net.nwtg.taleofbiomes.block.RiceCrop2Block;
import net.nwtg.taleofbiomes.block.RiceCrop1Block;
import net.nwtg.taleofbiomes.block.RiceCrop0Block;
import net.nwtg.taleofbiomes.block.QuicklimeBlockBlock;
import net.nwtg.taleofbiomes.block.PurplePiruffBedTopBlock;
import net.nwtg.taleofbiomes.block.PurplePiruffBedBlock;
import net.nwtg.taleofbiomes.block.PurpleAsterFlowerPotBlock;
import net.nwtg.taleofbiomes.block.PurpleAsterBlock;
import net.nwtg.taleofbiomes.block.PureCoalOreBlock;
import net.nwtg.taleofbiomes.block.PlotBlueprintBlock;
import net.nwtg.taleofbiomes.block.PiruffWoodBlock;
import net.nwtg.taleofbiomes.block.PiruffTrapdoorBlock;
import net.nwtg.taleofbiomes.block.PiruffStairsBlock;
import net.nwtg.taleofbiomes.block.PiruffSlabBlock;
import net.nwtg.taleofbiomes.block.PiruffPressurePlateBlock;
import net.nwtg.taleofbiomes.block.PiruffPlanksBlock;
import net.nwtg.taleofbiomes.block.PiruffLogBlock;
import net.nwtg.taleofbiomes.block.PiruffLeavesBlock;
import net.nwtg.taleofbiomes.block.PiruffFenceGateBlock;
import net.nwtg.taleofbiomes.block.PiruffFenceBlock;
import net.nwtg.taleofbiomes.block.PiruffDoorBlock;
import net.nwtg.taleofbiomes.block.PiruffButtonBlock;
import net.nwtg.taleofbiomes.block.PhosphoriteStoneBlock;
import net.nwtg.taleofbiomes.block.PhosphoriteShovelBlockBlock;
import net.nwtg.taleofbiomes.block.PhosphoriteRakeBlockBlock;
import net.nwtg.taleofbiomes.block.PhosphoriteHoeBlockBlock;
import net.nwtg.taleofbiomes.block.PhosphoriteCrystalTopBlock;
import net.nwtg.taleofbiomes.block.PhosphoriteCrystalBottomBlock;
import net.nwtg.taleofbiomes.block.PhosphoriteCrystalBlock;
import net.nwtg.taleofbiomes.block.PackedDirtBlock;
import net.nwtg.taleofbiomes.block.MagentaPiruffBedTopBlock;
import net.nwtg.taleofbiomes.block.MagentaPiruffBedBlock;
import net.nwtg.taleofbiomes.block.MagentaAsterFlowerPotBlock;
import net.nwtg.taleofbiomes.block.MagentaAsterBlock;
import net.nwtg.taleofbiomes.block.LimestoneBlock;
import net.nwtg.taleofbiomes.block.LightPurplePiruffBedTopBlock;
import net.nwtg.taleofbiomes.block.LightPurplePiruffBedBlock;
import net.nwtg.taleofbiomes.block.LargeBricksBlock;
import net.nwtg.taleofbiomes.block.LargeBrickWallBlock;
import net.nwtg.taleofbiomes.block.LargeBrickStairsBlock;
import net.nwtg.taleofbiomes.block.LargeBrickSlabBlock;
import net.nwtg.taleofbiomes.block.LargeBrickPressurePlateBlock;
import net.nwtg.taleofbiomes.block.LargeBrickButtonBlock;
import net.nwtg.taleofbiomes.block.KilnLadderBlock;
import net.nwtg.taleofbiomes.block.KilnFurnaceOnBlock;
import net.nwtg.taleofbiomes.block.KilnFurnaceBlock;
import net.nwtg.taleofbiomes.block.KilnBlockMiddleTopBlock;
import net.nwtg.taleofbiomes.block.KilnBlockMiddleCenterBlock;
import net.nwtg.taleofbiomes.block.KilnBlockMiddleBottomBlock;
import net.nwtg.taleofbiomes.block.KilnBlockFoundationBlock;
import net.nwtg.taleofbiomes.block.KilnBlockCornerTopBlock;
import net.nwtg.taleofbiomes.block.KilnBlockCornerCenterBlock;
import net.nwtg.taleofbiomes.block.KilnBlockCornerBottomBlock;
import net.nwtg.taleofbiomes.block.IvyShrubBlock;
import net.nwtg.taleofbiomes.block.HayStrawBlock;
import net.nwtg.taleofbiomes.block.HayGrassBlock;
import net.nwtg.taleofbiomes.block.HangingLanternOnBlock;
import net.nwtg.taleofbiomes.block.HangingLanternBlock;
import net.nwtg.taleofbiomes.block.GroundLanternOnBlock;
import net.nwtg.taleofbiomes.block.GroundLanternBlock;
import net.nwtg.taleofbiomes.block.GravelBlock;
import net.nwtg.taleofbiomes.block.GrassBlockBlock;
import net.nwtg.taleofbiomes.block.GoldenrodFlowerPotBlock;
import net.nwtg.taleofbiomes.block.GoldenrodBlock;
import net.nwtg.taleofbiomes.block.FertileSoilBlock;
import net.nwtg.taleofbiomes.block.DoorBlueprintBlock;
import net.nwtg.taleofbiomes.block.DirtBlock;
import net.nwtg.taleofbiomes.block.CobbledLimestoneBlock;
import net.nwtg.taleofbiomes.block.ClayBlockBlock;
import net.nwtg.taleofbiomes.block.BricksBlock;
import net.nwtg.taleofbiomes.block.BrickWallBlock;
import net.nwtg.taleofbiomes.block.BrickStairsBlock;
import net.nwtg.taleofbiomes.block.BrickSlabBlock;
import net.nwtg.taleofbiomes.block.BrickPressurePlateBlock;
import net.nwtg.taleofbiomes.block.BrickButtonBlock;
import net.nwtg.taleofbiomes.block.BluePiruffBedTopBlock;
import net.nwtg.taleofbiomes.block.BluePiruffBedBlock;
import net.nwtg.taleofbiomes.block.BlueAsterFlowerPotBlock;
import net.nwtg.taleofbiomes.block.BlueAsterBlock;
import net.nwtg.taleofbiomes.block.BasicToolTableBlock;
import net.nwtg.taleofbiomes.TaleOfBiomesMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.RegisterColorHandlersEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

public class TaleOfBiomesModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, TaleOfBiomesMod.MODID);
	public static final RegistryObject<Block> WALL_BLUEPRINT = REGISTRY.register("wall_blueprint", () -> new WallBlueprintBlock());
	public static final RegistryObject<Block> PLOT_BLUEPRINT = REGISTRY.register("plot_blueprint", () -> new PlotBlueprintBlock());
	public static final RegistryObject<Block> WINDOW_BLUEPRINT = REGISTRY.register("window_blueprint", () -> new WindowBlueprintBlock());
	public static final RegistryObject<Block> DOOR_BLUEPRINT = REGISTRY.register("door_blueprint", () -> new DoorBlueprintBlock());
	public static final RegistryObject<Block> BASIC_TOOL_TABLE = REGISTRY.register("basic_tool_table", () -> new BasicToolTableBlock());
	public static final RegistryObject<Block> KILN_FURNACE = REGISTRY.register("kiln_furnace", () -> new KilnFurnaceBlock());
	public static final RegistryObject<Block> BLUE_ASTER = REGISTRY.register("blue_aster", () -> new BlueAsterBlock());
	public static final RegistryObject<Block> PURPLE_ASTER = REGISTRY.register("purple_aster", () -> new PurpleAsterBlock());
	public static final RegistryObject<Block> MAGENTA_ASTER = REGISTRY.register("magenta_aster", () -> new MagentaAsterBlock());
	public static final RegistryObject<Block> GOLDENROD = REGISTRY.register("goldenrod", () -> new GoldenrodBlock());
	public static final RegistryObject<Block> WILD_INDIGO = REGISTRY.register("wild_indigo", () -> new WildIndigoBlock());
	public static final RegistryObject<Block> TALL_GRASS_0 = REGISTRY.register("tall_grass_0", () -> new TallGrass0Block());
	public static final RegistryObject<Block> TALL_GRASS_1 = REGISTRY.register("tall_grass_1", () -> new TallGrass1Block());
	public static final RegistryObject<Block> TALL_GRASS_2 = REGISTRY.register("tall_grass_2", () -> new TallGrass2Block());
	public static final RegistryObject<Block> HAY_GRASS = REGISTRY.register("hay_grass", () -> new HayGrassBlock());
	public static final RegistryObject<Block> HAY_STRAW = REGISTRY.register("hay_straw", () -> new HayStrawBlock());
	public static final RegistryObject<Block> IVY_SHRUB = REGISTRY.register("ivy_shrub", () -> new IvyShrubBlock());
	public static final RegistryObject<Block> ROSE_SHRUB = REGISTRY.register("rose_shrub", () -> new RoseShrubBlock());
	public static final RegistryObject<Block> PIRUFF_LEAVES = REGISTRY.register("piruff_leaves", () -> new PiruffLeavesBlock());
	public static final RegistryObject<Block> THATCH_BLOCK = REGISTRY.register("thatch_block", () -> new ThatchBlockBlock());
	public static final RegistryObject<Block> THATCH_STAIRS = REGISTRY.register("thatch_stairs", () -> new ThatchStairsBlock());
	public static final RegistryObject<Block> THATCH_SLAB = REGISTRY.register("thatch_slab", () -> new ThatchSlabBlock());
	public static final RegistryObject<Block> GRASS_BLOCK = REGISTRY.register("grass_block", () -> new GrassBlockBlock());
	public static final RegistryObject<Block> DIRT = REGISTRY.register("dirt", () -> new DirtBlock());
	public static final RegistryObject<Block> PACKED_DIRT = REGISTRY.register("packed_dirt", () -> new PackedDirtBlock());
	public static final RegistryObject<Block> FERTILE_SOIL = REGISTRY.register("fertile_soil", () -> new FertileSoilBlock());
	public static final RegistryObject<Block> TILLED_SOIL = REGISTRY.register("tilled_soil", () -> new TilledSoilBlock());
	public static final RegistryObject<Block> CLAY_BLOCK = REGISTRY.register("clay_block", () -> new ClayBlockBlock());
	public static final RegistryObject<Block> SAND = REGISTRY.register("sand", () -> new SandBlock());
	public static final RegistryObject<Block> GRAVEL = REGISTRY.register("gravel", () -> new GravelBlock());
	public static final RegistryObject<Block> PIRUFF_LOG = REGISTRY.register("piruff_log", () -> new PiruffLogBlock());
	public static final RegistryObject<Block> PIRUFF_WOOD = REGISTRY.register("piruff_wood", () -> new PiruffWoodBlock());
	public static final RegistryObject<Block> STRIPPED_PIRUFF_LOG = REGISTRY.register("stripped_piruff_log", () -> new StrippedPiruffLogBlock());
	public static final RegistryObject<Block> STRIPPED_PIRUFF_WOOD = REGISTRY.register("stripped_piruff_wood", () -> new StrippedPiruffWoodBlock());
	public static final RegistryObject<Block> PIRUFF_PLANKS = REGISTRY.register("piruff_planks", () -> new PiruffPlanksBlock());
	public static final RegistryObject<Block> PIRUFF_STAIRS = REGISTRY.register("piruff_stairs", () -> new PiruffStairsBlock());
	public static final RegistryObject<Block> PIRUFF_SLAB = REGISTRY.register("piruff_slab", () -> new PiruffSlabBlock());
	public static final RegistryObject<Block> PIRUFF_FENCE = REGISTRY.register("piruff_fence", () -> new PiruffFenceBlock());
	public static final RegistryObject<Block> PIRUFF_FENCE_GATE = REGISTRY.register("piruff_fence_gate", () -> new PiruffFenceGateBlock());
	public static final RegistryObject<Block> PIRUFF_DOOR = REGISTRY.register("piruff_door", () -> new PiruffDoorBlock());
	public static final RegistryObject<Block> PIRUFF_TRAPDOOR = REGISTRY.register("piruff_trapdoor", () -> new PiruffTrapdoorBlock());
	public static final RegistryObject<Block> PIRUFF_PRESSURE_PLATE = REGISTRY.register("piruff_pressure_plate", () -> new PiruffPressurePlateBlock());
	public static final RegistryObject<Block> PIRUFF_BUTTON = REGISTRY.register("piruff_button", () -> new PiruffButtonBlock());
	public static final RegistryObject<Block> LIMESTONE = REGISTRY.register("limestone", () -> new LimestoneBlock());
	public static final RegistryObject<Block> COBBLED_LIMESTONE = REGISTRY.register("cobbled_limestone", () -> new CobbledLimestoneBlock());
	public static final RegistryObject<Block> QUICKLIME_BLOCK = REGISTRY.register("quicklime_block", () -> new QuicklimeBlockBlock());
	public static final RegistryObject<Block> PHOSPHORITE_STONE = REGISTRY.register("phosphorite_stone", () -> new PhosphoriteStoneBlock());
	public static final RegistryObject<Block> PHOSPHORITE_CRYSTAL = REGISTRY.register("phosphorite_crystal", () -> new PhosphoriteCrystalBlock());
	public static final RegistryObject<Block> PHOSPHORITE_CRYSTAL_BOTTOM = REGISTRY.register("phosphorite_crystal_bottom", () -> new PhosphoriteCrystalBottomBlock());
	public static final RegistryObject<Block> PHOSPHORITE_CRYSTAL_TOP = REGISTRY.register("phosphorite_crystal_top", () -> new PhosphoriteCrystalTopBlock());
	public static final RegistryObject<Block> STONE = REGISTRY.register("stone", () -> new StoneBlock());
	public static final RegistryObject<Block> PURE_COAL_ORE = REGISTRY.register("pure_coal_ore", () -> new PureCoalOreBlock());
	public static final RegistryObject<Block> BRICKS = REGISTRY.register("bricks", () -> new BricksBlock());
	public static final RegistryObject<Block> BRICK_STAIRS = REGISTRY.register("brick_stairs", () -> new BrickStairsBlock());
	public static final RegistryObject<Block> BRICK_SLAB = REGISTRY.register("brick_slab", () -> new BrickSlabBlock());
	public static final RegistryObject<Block> BRICK_WALL = REGISTRY.register("brick_wall", () -> new BrickWallBlock());
	public static final RegistryObject<Block> BRICK_PRESSURE_PLATE = REGISTRY.register("brick_pressure_plate", () -> new BrickPressurePlateBlock());
	public static final RegistryObject<Block> BRICK_BUTTON = REGISTRY.register("brick_button", () -> new BrickButtonBlock());
	public static final RegistryObject<Block> LARGE_BRICKS = REGISTRY.register("large_bricks", () -> new LargeBricksBlock());
	public static final RegistryObject<Block> LARGE_BRICK_STAIRS = REGISTRY.register("large_brick_stairs", () -> new LargeBrickStairsBlock());
	public static final RegistryObject<Block> LARGE_BRICK_SLAB = REGISTRY.register("large_brick_slab", () -> new LargeBrickSlabBlock());
	public static final RegistryObject<Block> LARGE_BRICK_WALL = REGISTRY.register("large_brick_wall", () -> new LargeBrickWallBlock());
	public static final RegistryObject<Block> LARGE_BRICK_PRESSURE_PLATE = REGISTRY.register("large_brick_pressure_plate", () -> new LargeBrickPressurePlateBlock());
	public static final RegistryObject<Block> LARGE_BRICK_BUTTON = REGISTRY.register("large_brick_button", () -> new LargeBrickButtonBlock());
	public static final RegistryObject<Block> GROUND_LANTERN = REGISTRY.register("ground_lantern", () -> new GroundLanternBlock());
	public static final RegistryObject<Block> TOOL_HANDLE_BLOCK = REGISTRY.register("tool_handle_block", () -> new ToolHandleBlockBlock());
	public static final RegistryObject<Block> PHOSPHORITE_HOE_BLOCK = REGISTRY.register("phosphorite_hoe_block", () -> new PhosphoriteHoeBlockBlock());
	public static final RegistryObject<Block> PHOSPHORITE_SHOVEL_BLOCK = REGISTRY.register("phosphorite_shovel_block", () -> new PhosphoriteShovelBlockBlock());
	public static final RegistryObject<Block> PHOSPHORITE_RAKE_BLOCK = REGISTRY.register("phosphorite_rake_block", () -> new PhosphoriteRakeBlockBlock());
	public static final RegistryObject<Block> YELLOW_PIRUFF_BED = REGISTRY.register("yellow_piruff_bed", () -> new YellowPiruffBedBlock());
	public static final RegistryObject<Block> BLUE_PIRUFF_BED = REGISTRY.register("blue_piruff_bed", () -> new BluePiruffBedBlock());
	public static final RegistryObject<Block> PURPLE_PIRUFF_BED = REGISTRY.register("purple_piruff_bed", () -> new PurplePiruffBedBlock());
	public static final RegistryObject<Block> LIGHT_PURPLE_PIRUFF_BED = REGISTRY.register("light_purple_piruff_bed", () -> new LightPurplePiruffBedBlock());
	public static final RegistryObject<Block> MAGENTA_PIRUFF_BED = REGISTRY.register("magenta_piruff_bed", () -> new MagentaPiruffBedBlock());
	public static final RegistryObject<Block> BLUE_ASTER_FLOWER_POT = REGISTRY.register("blue_aster_flower_pot", () -> new BlueAsterFlowerPotBlock());
	public static final RegistryObject<Block> PURPLE_ASTER_FLOWER_POT = REGISTRY.register("purple_aster_flower_pot", () -> new PurpleAsterFlowerPotBlock());
	public static final RegistryObject<Block> MAGENTA_ASTER_FLOWER_POT = REGISTRY.register("magenta_aster_flower_pot", () -> new MagentaAsterFlowerPotBlock());
	public static final RegistryObject<Block> GOLDENROD_FLOWER_POT = REGISTRY.register("goldenrod_flower_pot", () -> new GoldenrodFlowerPotBlock());
	public static final RegistryObject<Block> WILD_INDIGO_FLOWER_POT = REGISTRY.register("wild_indigo_flower_pot", () -> new WildIndigoFlowerPotBlock());
	public static final RegistryObject<Block> TILLED_SOIL_W_1_S_0 = REGISTRY.register("tilled_soil_w_1_s_0", () -> new TilledSoilW1S0Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_1_S_1 = REGISTRY.register("tilled_soil_w_1_s_1", () -> new TilledSoilW1S1Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_1_S_2 = REGISTRY.register("tilled_soil_w_1_s_2", () -> new TilledSoilW1S2Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_1_S_3 = REGISTRY.register("tilled_soil_w_1_s_3", () -> new TilledSoilW1S3Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_1_S_4 = REGISTRY.register("tilled_soil_w_1_s_4", () -> new TilledSoilW1S4Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_2_S_0 = REGISTRY.register("tilled_soil_w_2_s_0", () -> new TilledSoilW2S0Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_2_S_1 = REGISTRY.register("tilled_soil_w_2_s_1", () -> new TilledSoilW2S1Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_2_S_2 = REGISTRY.register("tilled_soil_w_2_s_2", () -> new TilledSoilW2S2Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_2_S_3 = REGISTRY.register("tilled_soil_w_2_s_3", () -> new TilledSoilW2S3Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_2_S_4 = REGISTRY.register("tilled_soil_w_2_s_4", () -> new TilledSoilW2S4Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_3_S_0 = REGISTRY.register("tilled_soil_w_3_s_0", () -> new TilledSoilW3S0Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_3_S_1 = REGISTRY.register("tilled_soil_w_3_s_1", () -> new TilledSoilW3S1Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_3_S_2 = REGISTRY.register("tilled_soil_w_3_s_2", () -> new TilledSoilW3S2Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_3_S_3 = REGISTRY.register("tilled_soil_w_3_s_3", () -> new TilledSoilW3S3Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_3_S_4 = REGISTRY.register("tilled_soil_w_3_s_4", () -> new TilledSoilW3S4Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_4_S_0 = REGISTRY.register("tilled_soil_w_4_s_0", () -> new TilledSoilW4S0Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_4_S_1 = REGISTRY.register("tilled_soil_w_4_s_1", () -> new TilledSoilW4S1Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_4_S_2 = REGISTRY.register("tilled_soil_w_4_s_2", () -> new TilledSoilW4S2Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_4_S_3 = REGISTRY.register("tilled_soil_w_4_s_3", () -> new TilledSoilW4S3Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_4_S_4 = REGISTRY.register("tilled_soil_w_4_s_4", () -> new TilledSoilW4S4Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_0_S_1 = REGISTRY.register("tilled_soil_w_0_s_1", () -> new TilledSoilW0S1Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_0_S_2 = REGISTRY.register("tilled_soil_w_0_s_2", () -> new TilledSoilW0S2Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_0_S_3 = REGISTRY.register("tilled_soil_w_0_s_3", () -> new TilledSoilW0S3Block());
	public static final RegistryObject<Block> TILLED_SOIL_W_0_S_4 = REGISTRY.register("tilled_soil_w_0_s_4", () -> new TilledSoilW0S4Block());
	public static final RegistryObject<Block> KILN_FURNACE_ON = REGISTRY.register("kiln_furnace_on", () -> new KilnFurnaceOnBlock());
	public static final RegistryObject<Block> KILN_LADDER = REGISTRY.register("kiln_ladder", () -> new KilnLadderBlock());
	public static final RegistryObject<Block> KILN_BLOCK_CORNER_BOTTOM = REGISTRY.register("kiln_block_corner_bottom", () -> new KilnBlockCornerBottomBlock());
	public static final RegistryObject<Block> KILN_BLOCK_CORNER_CENTER = REGISTRY.register("kiln_block_corner_center", () -> new KilnBlockCornerCenterBlock());
	public static final RegistryObject<Block> KILN_BLOCK_CORNER_TOP = REGISTRY.register("kiln_block_corner_top", () -> new KilnBlockCornerTopBlock());
	public static final RegistryObject<Block> KILN_BLOCK_MIDDLE_BOTTOM = REGISTRY.register("kiln_block_middle_bottom", () -> new KilnBlockMiddleBottomBlock());
	public static final RegistryObject<Block> KILN_BLOCK_MIDDLE_CENTER = REGISTRY.register("kiln_block_middle_center", () -> new KilnBlockMiddleCenterBlock());
	public static final RegistryObject<Block> KILN_BLOCK_MIDDLE_TOP = REGISTRY.register("kiln_block_middle_top", () -> new KilnBlockMiddleTopBlock());
	public static final RegistryObject<Block> KILN_BLOCK_FOUNDATION = REGISTRY.register("kiln_block_foundation", () -> new KilnBlockFoundationBlock());
	public static final RegistryObject<Block> RICE_CROP_0 = REGISTRY.register("rice_crop_0", () -> new RiceCrop0Block());
	public static final RegistryObject<Block> RICE_CROP_1 = REGISTRY.register("rice_crop_1", () -> new RiceCrop1Block());
	public static final RegistryObject<Block> RICE_CROP_2 = REGISTRY.register("rice_crop_2", () -> new RiceCrop2Block());
	public static final RegistryObject<Block> RICE_CROP_3 = REGISTRY.register("rice_crop_3", () -> new RiceCrop3Block());
	public static final RegistryObject<Block> RICE_CROP_4 = REGISTRY.register("rice_crop_4", () -> new RiceCrop4Block());
	public static final RegistryObject<Block> RICE_CROP_5 = REGISTRY.register("rice_crop_5", () -> new RiceCrop5Block());
	public static final RegistryObject<Block> RICE_CROP_6 = REGISTRY.register("rice_crop_6", () -> new RiceCrop6Block());
	public static final RegistryObject<Block> RICE_CROP_7 = REGISTRY.register("rice_crop_7", () -> new RiceCrop7Block());
	public static final RegistryObject<Block> HANGING_LANTERN = REGISTRY.register("hanging_lantern", () -> new HangingLanternBlock());
	public static final RegistryObject<Block> HANGING_LANTERN_ON = REGISTRY.register("hanging_lantern_on", () -> new HangingLanternOnBlock());
	public static final RegistryObject<Block> GROUND_LANTERN_ON = REGISTRY.register("ground_lantern_on", () -> new GroundLanternOnBlock());
	public static final RegistryObject<Block> YELLOW_PIRUFF_BED_TOP = REGISTRY.register("yellow_piruff_bed_top", () -> new YellowPiruffBedTopBlock());
	public static final RegistryObject<Block> BLUE_PIRUFF_BED_TOP = REGISTRY.register("blue_piruff_bed_top", () -> new BluePiruffBedTopBlock());
	public static final RegistryObject<Block> LIGHT_PURPLE_PIRUFF_BED_TOP = REGISTRY.register("light_purple_piruff_bed_top", () -> new LightPurplePiruffBedTopBlock());
	public static final RegistryObject<Block> MAGENTA_PIRUFF_BED_TOP = REGISTRY.register("magenta_piruff_bed_top", () -> new MagentaPiruffBedTopBlock());
	public static final RegistryObject<Block> PURPLE_PIRUFF_BED_TOP = REGISTRY.register("purple_piruff_bed_top", () -> new PurplePiruffBedTopBlock());

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			TallGrass0Block.blockColorLoad(event);
			TallGrass1Block.blockColorLoad(event);
			TallGrass2Block.blockColorLoad(event);
			HayGrassBlock.blockColorLoad(event);
			PiruffLeavesBlock.blockColorLoad(event);
			GrassBlockBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(RegisterColorHandlersEvent.Item event) {
			TallGrass0Block.itemColorLoad(event);
			TallGrass1Block.itemColorLoad(event);
			TallGrass2Block.itemColorLoad(event);
			HayGrassBlock.itemColorLoad(event);
			PiruffLeavesBlock.itemColorLoad(event);
			GrassBlockBlock.itemColorLoad(event);
		}
	}
}
